select * from constomer limit 20;

ALTER TABLE constomer RENAME TO customer;
--1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as revenue
from customer
group by gender;

--2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied='Yes' and purchase_amount >= (select avg(purchase_amount) from customer);

--3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating::numeric),2) as avg_review_rating
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type, round(avg(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

--5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status, count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spent,
sum(purchase_amount) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spent;

--6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
round(sum(case when discount_applied='Yes' then 1 else 0 end)*100/count(*), 2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
WITH customer_type AS (
    SELECT customer_id, previous_purchases,
    CASE 
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment
    FROM customer	
)

SELECT customer_segment, COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment;

--8. What are the top 3 most purchased products within each category?
with item_counts as(
select category, item_purchased,
count (customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id)desc) as item_rank
from customer
group by  category, item_purchased

)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank >= 3;

--9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(customer_id) as repeat_buyers
from customer
where previous_purchases >5
group by subscription_status;

--10. What is the revenue contribution of each age group?
select age_group, count(purchase_amount) total_revenue
from customer 
group by age_group
order by total_revenue desc;